### ISSUE TITLE
Unexpected value 'ColorPickerModule' imported by the module

### ISSUE THREAD

**Issue by fahad-nxvt** [Alberplz/angular2-color-picker#66]
Updated angular to 2.3.0 and start getting this error 

**Unexpected value 'ColorPickerModule' imported by the module**

Anyone knows how to fix this?

**Comment by curlyfro** [comment]
i just upgraded from angular 2.1 to 2.3 and i'm getting the same error.

**Comment by curlyfro** [comment]
fixed.  i npm uninstalled then re-installed the package and that fixed it.

**Comment by jonohrt** [comment]
I also just updated from angular 2.1 to 2.3 and I'm also getting this error. I uninstalled and re-installed the package and the error persists. Deleted node_modules and re-installed and still I'm still getting the error. Any idea?

**Comment by fahad-nxvt** [comment]
I uninstalled and installed it many times but no luck.

**Comment by MoxxNull** [comment]
I have the same error ... uninstalling / reinstalling does not help

**Comment by fahad-nxvt** [comment]
any luck anyone?

**Comment by Unlockedluca** [comment]
i get the error "Unexpected Value 'e' in Modules..." using Angular2, TypeScript with WebPack.
Installed colorpicker with npm

**Comment by garethlewis** [comment]
You're getting that error as the color picker is tied to Angular 2.1.0, is there was a change such as 2.1.1 onwards it would work, but the package.json has Angular referenced as ~2.1.0, so it will not use 2.2.0 or 2.3.0.  If you're using SystemJS, you will not notice this problem, as it will download the version of Angular 2 needed for the color picker and also the version of Angular 2 for your app.  The problem occurs when using Webpack.  It is trying to consolidate the code into a single file, usually vendor.js, and this ends up being incorrect, as the differences between Angular 2.1.0 and Angular 2.2.0 will throw the packer off.

**Comment by MoxxNull** [comment]
Hm.. any workaround for that? (As I assume it will always happen when my angular version is ahead of color-picker's angulas version?)

**Comment by garethlewis** [comment]
The only way I would recommend fixing this is to fork the repository and build from source yourself into a package that you can use.  Then change the referenced version of angular to whichever version you need to use.

The pros:
You are in charge of the Angular version used.
The cons:
Your fork will not contain any new changes made to the main repo.  You will have to switch to that branch and merge in those changes to your fork.  As long as your fork isn't too old, you should not have any problems.  But if you start making changes to any of the files, you run the usual risk of merge conflicts which may be difficult to resolve without prior knowledge.

**Comment by raducostea** [comment]
@BrainCrumbz Where can i find your build?

**Comment by BrainCrumbz** [comment]
Just pushed, you can find it at [ng2-aot-color-picker-sample](https://github.com/BrainCrumbz/ng2-aot-color-picker-sample) together with some instructions. HTH

**Comment by sconix** [comment]
I have also a working AOT version and I plan to make PR as soon as I fix the example apps. I can post url to the github repo as soon as I have made the PR, the repo will have a npm-package branch that can be used to install the aot version through npm.

**Comment by fospitia** [comment]
Thanks @sconix but in the npm-package branch the *.js files aren't compiled, are the same *.ts files

**Comment by sconix** [comment]
They are, I can't see how they could be the same as ts files. The js files are produced by the ngc compiler.

**Comment by fospitia** [comment]
I use webpack and this commit work for me git://github.com/zefoy/angular2-color-picker.git#cc12b8b516ce85f237ba62da4f7b75f731476ada

**Comment by sconix** [comment]
We use angular-cli in our project which uses webpack and the npm-package branch works nicely. There is also aot-fixes branch where you have the exact same build files as in npm-package and the both systemjs and webpack example apps work nicely when using the the library.

**Comment by BearandYoon** [comment]
I am using angular-cli and angular2-color-picker but it is not working for me.

  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.4.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@types/socket.io-client": "^1.4.29",
    "angular2-color-picker": "^1.3.0",
    "chart.js": "2.3.0",
    "core-js": "^2.4.1",
    "moment": "2.15.2",
    "ng2-bootstrap": "^1.1.16",
    "ng2-charts": "1.4.1",
    "rxjs": "^5.0.0-rc.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.26"
  },

It is working for you?

**Comment by sconix** [comment]
There is a working version which can be installed from: git://github.com/zefoy/angular2-color-picker.git#npm-package

The released version is broken since angular-cli made the change that libs need to be AOT compatible. I have made a pull request and tried to contact the developer to get new release out but so far no luck.

**Comment by BearandYoon** [comment]
@sconix 
It works very well.
Thanks.

**Comment by zskhan** [comment]
Please refer this: https://github.com/Alberplz/angular2-color-picker/issues/82
